[book]
authors = ["Zhuang Biaowei","Wang Wei"]
language = "zh"
multilingual = true
src = "src"
title = "开源社 —— 开源书籍"

[build]
create-missing = false

[preprocessor.echarts]

[output.html]
additional-js = ["assets/echarts.min.js","assets/MathJax.js"]

[output.html.fold]
enable = true
level = 0
